name: Continuous Delivery

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-34-jdk17
    env:
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Decode keystore
        run: echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks
      - name: Build APK AAB
        run: ./gradlew assembleRelease bundleRelease
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
