name: Continuous Integration

on:
  pull_request: null
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-34-jdk17
    env:
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
    steps:
      - uses: actions/checkout@v4
      - name: Decode keystore
        run: echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks
      - name: Build APK
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/release/*.apk
